// admin/src/pages/resume/WorkTab.tsx
import { useState, useEffect, useCallback } from 'react'
import { LoaderIcon, PlusIcon, PencilIcon, Trash2Icon } from 'lucide-react'
import { api } from '../../lib/api'
import type { ResumeLocale, ResumeWorkItem } from '../../lib/api'
import type { WorkDraft } from '../../types/resume'
import {
  Field,
  inputCls,
  textareaCls,
  btnPrimary,
  btnGhost,
} from '../../components/form'
import { Loader, Empty, FormActions, LocaleSwitcher } from './shared'

const EMPTY_WORK: WorkDraft = {
  locale: 'en',
  company: '',
  link: '',
  badge: '',
  title: '',
  start: '',
  end: '',
  description: '',
  sortOrder: 0,
}

export function WorkTab() {
  const [locale, setLocale] = useState<ResumeLocale>('en')
  const [items, setItems] = useState<ResumeWorkItem[]>([])
  const [loading, setLoading] = useState(true)
  const [editingId, setEditingId] = useState<number | 'new' | null>(null)
  const [draft, setDraft] = useState<WorkDraft>(EMPTY_WORK)
  const [saving, setSaving] = useState(false)
  const [copying, setCopying] = useState(false)

  const load = useCallback(async (l: ResumeLocale) => {
    setLoading(true)
    try {
      setItems(await api.resume.listWork(l))
    } catch {
      setItems([])
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void load(locale)
  }, [locale, load])

  function startAdd() {
    setDraft({ ...EMPTY_WORK, locale })
    setEditingId('new')
  }

  function startEdit(item: ResumeWorkItem) {
    setDraft({
      locale: item.locale,
      company: item.company,
      link: item.link,
      badge: item.badge,
      title: item.title,
      start: item.start,
      end: item.end,
      description: item.description,
      sortOrder: item.sortOrder,
    })
    setEditingId(item.id)
  }

  function setField(key: keyof WorkDraft, value: string | number) {
    setDraft((p) => ({ ...p, [key]: value }))
  }

  async function handleSave() {
    setSaving(true)
    try {
      if (editingId === 'new') {
        const created = await api.resume.createWork(draft)
        setItems((p) => [...p, created])
      } else if (editingId !== null) {
        const updated = await api.resume.updateWork(editingId, draft)
        setItems((p) => p.map((i) => (i.id === editingId ? updated : i)))
      }
      setEditingId(null)
    } catch (err) {
      alert(`Save failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      setSaving(false)
    }
  }

  async function handleDelete(id: number, label: string) {
    if (!confirm(`Delete "${label}"?`)) return
    await api.resume.deleteWork(id)
    setItems((p) => p.filter((i) => i.id !== id))
  }

  async function handleCopy() {
    const from: ResumeLocale = locale === 'id' ? 'en' : 'id'
    if (
      !confirm(
        `Copy all ${from.toUpperCase()} entries to ${locale.toUpperCase()}? This will overwrite existing ${locale.toUpperCase()} work entries.`,
      )
    )
      return
    setCopying(true)
    try {
      const copied = await api.resume.copyWork(from, locale)
      setItems(copied)
    } catch (err) {
      alert(`Copy failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      setCopying(false)
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <LocaleSwitcher
          locale={locale}
          onChange={(l) => {
            setLocale(l)
            setEditingId(null)
          }}
        />
        <div className="flex gap-2">
          <button onClick={handleCopy} disabled={copying} className={btnGhost}>
            {copying ? (
              <LoaderIcon size={12} className="mr-1 inline animate-spin" />
            ) : null}
            Copy from {locale === 'id' ? 'EN' : 'ID'}
          </button>
          <button onClick={startAdd} className={btnPrimary}>
            <PlusIcon size={12} /> Add
          </button>
        </div>
      </div>

      {loading ? (
        <Loader />
      ) : (
        <div className="divide-y divide-black/10 border border-black/10 dark:divide-white/10 dark:border-white/10">
          {editingId === 'new' && (
            <WorkForm
              draft={draft}
              setField={setField}
              saving={saving}
              onSave={handleSave}
              onCancel={() => setEditingId(null)}
            />
          )}
          {items.map((item) =>
            editingId === item.id ? (
              <WorkForm
                key={item.id}
                draft={draft}
                setField={setField}
                saving={saving}
                onSave={handleSave}
                onCancel={() => setEditingId(null)}
              />
            ) : (
              <div
                key={item.id}
                className="flex items-center gap-3 px-4 py-3 hover:bg-black/5 dark:hover:bg-white/5"
              >
                <div className="min-w-0 flex-1">
                  <p className="text-sm font-bold">
                    {item.company}{' '}
                    <span className="font-normal text-black/50 dark:text-white/50">
                      — {item.title}
                    </span>
                  </p>
                  <p className="font-mono text-xs text-black/40 dark:text-white/40">
                    {item.start}–{item.end}
                  </p>
                </div>
                <button
                  onClick={() => startEdit(item)}
                  className="p-1.5 text-black/30 hover:text-black dark:text-white/30 dark:hover:text-white"
                >
                  <PencilIcon size={13} />
                </button>
                <button
                  onClick={() => handleDelete(item.id, item.company)}
                  className="p-1.5 text-black/30 hover:bg-red-500 hover:text-white dark:text-white/30"
                >
                  <Trash2Icon size={13} />
                </button>
              </div>
            ),
          )}
          {items.length === 0 && editingId !== 'new' && <Empty />}
        </div>
      )}
    </div>
  )
}

function WorkForm({
  draft,
  setField,
  saving,
  onSave,
  onCancel,
}: {
  draft: WorkDraft
  setField: (k: keyof WorkDraft, v: string | number) => void
  saving: boolean
  onSave: () => void
  onCancel: () => void
}) {
  return (
    <div className="space-y-3 bg-black/5 p-4 dark:bg-white/5">
      <div className="grid grid-cols-2 gap-3">
        <Field label="Company">
          <input
            className={inputCls}
            value={draft.company}
            onChange={(e) => setField('company', e.target.value)}
          />
        </Field>
        <Field label="Title">
          <input
            className={inputCls}
            value={draft.title}
            onChange={(e) => setField('title', e.target.value)}
          />
        </Field>
        <Field label="Start">
          <input
            className={inputCls}
            value={draft.start}
            onChange={(e) => setField('start', e.target.value)}
            placeholder="2022"
          />
        </Field>
        <Field label="End">
          <input
            className={inputCls}
            value={draft.end}
            onChange={(e) => setField('end', e.target.value)}
            placeholder="Now"
          />
        </Field>
        <Field label="Link">
          <input
            className={inputCls}
            value={draft.link}
            onChange={(e) => setField('link', e.target.value)}
          />
        </Field>
        <Field label="Sort Order">
          <input
            type="number"
            className={inputCls}
            value={draft.sortOrder}
            onChange={(e) => setField('sortOrder', Number(e.target.value))}
          />
        </Field>
      </div>
      <Field label="Description">
        <textarea
          rows={2}
          className={textareaCls}
          value={draft.description}
          onChange={(e) => setField('description', e.target.value)}
        />
      </Field>
      <FormActions saving={saving} onSave={onSave} onCancel={onCancel} />
    </div>
  )
}

// admin/src/lib/components/resume/WorkTab.svelte
<script lang="ts">
  import { Loader, Plus, Pencil, Trash2, Check, X } from 'lucide-svelte'
  import type { Lang, ResumeWorkItem, WorkDraft } from '$lib/types'
  import { api } from '$lib/api'

  const inputCls = 'w-full border border-black/20 bg-transparent px-3 py-1.5 text-sm outline-none focus:border-black dark:border-white/20 dark:focus:border-white'
  const textareaCls = 'w-full resize-y border border-black/20 bg-transparent px-3 py-1.5 text-sm outline-none focus:border-black dark:border-white/20 dark:focus:border-white'
  const btnPrimary = 'flex items-center gap-1.5 bg-black px-3 py-1.5 text-xs font-bold tracking-wide text-white uppercase transition-colors hover:bg-black/80 disabled:opacity-40 dark:bg-white dark:text-black dark:hover:bg-white/80'
  const btnGhost = 'px-3 py-1.5 font-mono text-xs tracking-widest text-black/40 uppercase transition-colors hover:text-black dark:text-white/40 dark:hover:text-white'
  const labelCls = 'font-mono text-[10px] font-bold tracking-widest text-black/50 uppercase dark:text-white/50'

  const EMPTY: WorkDraft = { locale: 'en', company: '', link: '', badge: '', title: '', start: '', end: '', description: '', sortOrder: 0 }

  let locale = $state<Lang>('en')
  let items = $state<ResumeWorkItem[]>([])
  let loading = $state(true)
  let editingId = $state<number | 'new' | null>(null)
  let draft = $state<WorkDraft>({ ...EMPTY })
  let saving = $state(false)
  let copying = $state(false)

  async function load(l: Lang) {
    loading = true
    try {
      items = await api.listResumeWork(l)
    } catch {
      items = []
    } finally {
      loading = false
    }
  }

  $effect(() => { void load(locale) })

  function startAdd() {
    draft = { ...EMPTY, locale }
    editingId = 'new'
  }

  function startEdit(item: ResumeWorkItem) {
    draft = { locale: item.locale, company: item.company, link: item.link, badge: item.badge, title: item.title, start: item.start, end: item.end, description: item.description, sortOrder: item.sortOrder }
    editingId = item.id
  }

  function setField<K extends keyof WorkDraft>(key: K, value: WorkDraft[K]) {
    draft = { ...draft, [key]: value }
  }

  async function handleSave() {
    saving = true
    try {
      if (editingId === 'new') {
        const created = await api.createResumeWork({ ...draft, locale })
        items = [...items, created]
      } else if (editingId !== null) {
        const updated = await api.updateResumeWork(editingId, draft)
        items = items.map((i) => (i.id === editingId ? updated : i))
      }
      editingId = null
    } catch (err) {
      alert(`Save failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      saving = false
    }
  }

  async function handleDelete(id: number, label: string) {
    if (!confirm(`Delete "${label}"?`)) return
    await api.deleteResumeWork(id)
    items = items.filter((i) => i.id !== id)
  }

  async function handleCopy() {
    const from: Lang = locale === 'id' ? 'en' : 'id'
    if (!confirm(`Copy all ${from.toUpperCase()} entries to ${locale.toUpperCase()}? This will overwrite existing ${locale.toUpperCase()} work entries.`)) return
    copying = true
    try {
      items = await api.copyResumeWork(from, locale)
    } catch (err) {
      alert(`Copy failed: ${err instanceof Error ? err.message : String(err)}`)
    } finally {
      copying = false
    }
  }
</script>

<div class="space-y-4">
  <div class="flex items-center justify-between">
    <div class="flex gap-1">
      {#each ['en', 'id'] as l}
        <button
          type="button"
          onclick={() => { locale = l as Lang; editingId = null }}
          class={['px-2.5 py-1 font-mono text-[10px] font-bold tracking-widest uppercase transition-colors', locale === l ? 'bg-black text-white dark:bg-white dark:text-black' : 'text-black/30 hover:text-black dark:text-white/30 dark:hover:text-white'].join(' ')}
        >{l.toUpperCase()}</button>
      {/each}
    </div>
    <div class="flex gap-2">
      <button onclick={handleCopy} disabled={copying} class={btnGhost}>
        {#if copying}<Loader size={12} class="mr-1 inline animate-spin" />{/if}
        Copy from {locale === 'id' ? 'EN' : 'ID'}
      </button>
      <button onclick={startAdd} class={btnPrimary}><Plus size={12} /> Add</button>
    </div>
  </div>

  {#if loading}
    <p class="font-mono text-xs tracking-widest text-black/40 uppercase dark:text-white/40">Loading...</p>
  {:else}
    <div class="divide-y divide-black/10 border border-black/10 dark:divide-white/10 dark:border-white/10">
      {#if editingId === 'new'}
        <div class="space-y-3 bg-black/5 p-4 dark:bg-white/5">
          <div class="grid grid-cols-2 gap-3">
            <div class="flex flex-col gap-1"><label class={labelCls}>Company</label><input class={inputCls} value={draft.company} oninput={(e) => setField('company', (e.target as HTMLInputElement).value)} /></div>
            <div class="flex flex-col gap-1"><label class={labelCls}>Title</label><input class={inputCls} value={draft.title} oninput={(e) => setField('title', (e.target as HTMLInputElement).value)} /></div>
            <div class="flex flex-col gap-1"><label class={labelCls}>Start</label><input class={inputCls} value={draft.start} placeholder="2022" oninput={(e) => setField('start', (e.target as HTMLInputElement).value)} /></div>
            <div class="flex flex-col gap-1"><label class={labelCls}>End</label><input class={inputCls} value={draft.end} placeholder="Now" oninput={(e) => setField('end', (e.target as HTMLInputElement).value)} /></div>
            <div class="flex flex-col gap-1"><label class={labelCls}>Link</label><input class={inputCls} value={draft.link} oninput={(e) => setField('link', (e.target as HTMLInputElement).value)} /></div>
            <div class="flex flex-col gap-1"><label class={labelCls}>Sort Order</label><input type="number" class={inputCls} value={draft.sortOrder} oninput={(e) => setField('sortOrder', Number((e.target as HTMLInputElement).value))} /></div>
          </div>
          <div class="flex flex-col gap-1"><label class={labelCls}>Description</label><textarea rows={2} class={textareaCls} value={draft.description} oninput={(e) => setField('description', (e.target as HTMLTextAreaElement).value)}></textarea></div>
          <div class="flex gap-2">
            <button type="button" onclick={handleSave} disabled={saving} class={btnPrimary}>{#if saving}<Loader size={12} class="animate-spin" />{:else}<Check size={12} />{/if} Save</button>
            <button type="button" onclick={() => (editingId = null)} class={btnGhost}>Cancel</button>
          </div>
        </div>
      {/if}

      {#each items as item (item.id)}
        {#if editingId === item.id}
          <div class="space-y-3 bg-black/5 p-4 dark:bg-white/5">
            <div class="grid grid-cols-2 gap-3">
              <div class="flex flex-col gap-1"><label class={labelCls}>Company</label><input class={inputCls} value={draft.company} oninput={(e) => setField('company', (e.target as HTMLInputElement).value)} /></div>
              <div class="flex flex-col gap-1"><label class={labelCls}>Title</label><input class={inputCls} value={draft.title} oninput={(e) => setField('title', (e.target as HTMLInputElement).value)} /></div>
              <div class="flex flex-col gap-1"><label class={labelCls}>Start</label><input class={inputCls} value={draft.start} placeholder="2022" oninput={(e) => setField('start', (e.target as HTMLInputElement).value)} /></div>
              <div class="flex flex-col gap-1"><label class={labelCls}>End</label><input class={inputCls} value={draft.end} placeholder="Now" oninput={(e) => setField('end', (e.target as HTMLInputElement).value)} /></div>
              <div class="flex flex-col gap-1"><label class={labelCls}>Link</label><input class={inputCls} value={draft.link} oninput={(e) => setField('link', (e.target as HTMLInputElement).value)} /></div>
              <div class="flex flex-col gap-1"><label class={labelCls}>Sort Order</label><input type="number" class={inputCls} value={draft.sortOrder} oninput={(e) => setField('sortOrder', Number((e.target as HTMLInputElement).value))} /></div>
            </div>
            <div class="flex flex-col gap-1"><label class={labelCls}>Description</label><textarea rows={2} class={textareaCls} value={draft.description} oninput={(e) => setField('description', (e.target as HTMLTextAreaElement).value)}></textarea></div>
            <div class="flex gap-2">
              <button type="button" onclick={handleSave} disabled={saving} class={btnPrimary}>{#if saving}<Loader size={12} class="animate-spin" />{:else}<Check size={12} />{/if} Save</button>
              <button type="button" onclick={() => (editingId = null)} class={btnGhost}>Cancel</button>
            </div>
          </div>
        {:else}
          <div class="flex items-center gap-3 px-4 py-3 hover:bg-black/5 dark:hover:bg-white/5">
            <div class="min-w-0 flex-1">
              <p class="text-sm font-bold">{item.company} <span class="font-normal text-black/50 dark:text-white/50">— {item.title}</span></p>
              <p class="font-mono text-xs text-black/40 dark:text-white/40">{item.start}–{item.end}</p>
            </div>
            <button onclick={() => startEdit(item)} class="p-1.5 text-black/30 hover:text-black dark:text-white/30 dark:hover:text-white"><Pencil size={13} /></button>
            <button onclick={() => handleDelete(item.id, item.company)} class="p-1.5 text-black/30 hover:bg-red-500 hover:text-white dark:text-white/30"><Trash2 size={13} /></button>
          </div>
        {/if}
      {/each}

      {#if items.length === 0 && editingId !== 'new'}
        <div class="px-4 py-6 text-center font-mono text-xs tracking-widest text-black/30 uppercase dark:text-white/30">No entries yet.</div>
      {/if}
    </div>
  {/if}
</div>
